name: Push NuGet Packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Setup Blazor Deps
      run: |
        dotnet workload install wasm-tools
    - name: Setup csproj files
      run: |
        sed 's/9999/'${{ github.run_number }}-alpha'/g' src/Cronograph/Cronograph.csproj > src/Cronograph/Cronograph.final.csproj
        cp src/Cronograph/Cronograph.final.csproj src/Cronograph/Cronograph.csproj
        sed 's/9999/'${{ github.run_number }}-alpha'/g' src/Cronograph.UI/Cronograph.UI.csproj > src/Cronograph.UI/Cronograph.UI.final.csproj
        cp src/Cronograph.UI/Cronograph.UI.final.csproj src/Cronograph.UI/Cronograph.UI.csproj
        sed 's/9999/'${{ github.run_number }}-alpha'/g' src/Cronograph.Shared/Cronograph.Shared.csproj > src/Cronograph.Shared/Cronograph.Shared.final.csproj
        cp src/Cronograph.Shared/Cronograph.Shared.final.csproj src/Cronograph.Shared/Cronograph.Shared.csproj
        sed 's/9999/'${{ github.run_number }}-alpha'/g' src/Cronograph.MongoDb/Cronograph.MongoDb.csproj > src/Cronograph.MongoDb/Cronograph.MongoDb.final.csproj
        cp src/Cronograph.MongoDb/Cronograph.MongoDb.final.csproj src/Cronograph.MongoDb/Cronograph.MongoDb.csproj
    - name: Build Cronograph
      run: |
        dotnet build src/Cronograph.Shared/Cronograph.Shared.csproj --configuration Release
        dotnet build src/Cronograph/Cronograph.csproj --configuration Release
        dotnet build src/Cronograph.Client/Cronograph.Client.csproj --configuration Release
        dotnet publish src/Cronograph.Client/Cronograph.Client.csproj --configuration Release --output src/blazor
        dotnet build src/Cronograph.UI/Cronograph.UI.csproj --configuration Release
        dotnet build src/Cronograph.UI/Cronograph.MongoDb.csproj --configuration Release
    - name: Test
      run: dotnet test src --configuration Release --no-build --verbosity normal
    - name: Pack
      run: |
        dotnet pack src/Cronograph.Shared/Cronograph.Shared.csproj -o packages --configuration Release --no-build --verbosity normal -p:PackageVersion=1.0.${{ github.run_number }}
        dotnet pack src/Cronograph/Cronograph.csproj -o packages --configuration Release --no-build --verbosity normal -p:PackageVersion=1.0.${{ github.run_number }}
        dotnet pack src/Cronograph.UI/Cronograph.UI.csproj -o packages --configuration Release --no-build --verbosity normal -p:PackageVersion=1.0.${{ github.run_number }}
        dotnet pack src/Cronograph.UI/Cronograph.MongoDb.csproj -o packages --configuration Release --no-build --verbosity normal -p:PackageVersion=1.0.${{ github.run_number }}
    - name: Push
      run: |
       dotnet nuget push packages/Cronograph.1.0.${{ github.run_number }}.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
       dotnet nuget push packages/Cronograph.UI.1.0.${{ github.run_number }}.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
       dotnet nuget push packages/Cronograph.Shared.1.0.${{ github.run_number }}.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
       dotnet nuget push packages/Cronograph.MongoDb.1.0.${{ github.run_number }}.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
